---
- name: create user
  user:
    name: "{{ dofus_market_bot_user }}"
    comment: Owner of the Dofus Market bot

- name: create service
  template:
    src: "{{ dofus_market_bot_service_name }}.service.j2"
    dest: "/lib/systemd/system/{{ dofus_market_bot_service_name }}.service"
    mode: 0644

- name: build
  become: false
  command: "dotnet publish -c Release {{ playbook_dir | dirname }}/src/DofusMarket.Bot --output /tmp/{{ dofus_market_bot_path | basename }}_new"
  delegate_to: localhost

- name: compress locally
  archive:
    path: "/tmp/{{ dofus_market_bot_path | basename }}_new"
    dest: "/tmp/{{ dofus_market_bot_path | basename }}_new.tgz"
  delegate_to: localhost
  become: false

- name: copy to host and decompress
  unarchive:
    src: "/tmp/{{ dofus_market_bot_path | basename }}_new.tgz"
    dest: "{{ dofus_market_bot_path | dirname }}"
    mode: u=rwX,g=,o=
    owner: "{{ dofus_market_bot_user }}"
    group: "{{ dofus_market_bot_user }}"
  become_user: "{{ dofus_market_bot_user }}" # https://github.com/ansible/ansible/issues/35426

- name: generate settings
  template:
    src: appsettings.Production.json.j2
    dest: "{{ dofus_market_bot_path }}_new/appsettings.Production.json"
    mode: 0600
    owner: "{{ dofus_market_bot_user }}"
    group: "{{ dofus_market_bot_user }}"
  notify:
    - reload systemd

- name: check that a version is already present
  stat:
    path: "{{ dofus_market_bot_path }}"
  register: dofus_market_bot_path_stat_result

- name: create log folder
  file:
    path: "{{ dofus_market_bot_log_file | dirname }}"
    state: directory
    mode: 0755
    group: "{{ dofus_market_bot_user }}"
    owner: "{{ dofus_market_bot_user }}"

- name: stop service
  service:
    name: "{{ dofus_market_bot_service_name }}"
    enabled: yes
    state: stopped

- name: swap old and new version (1/2)
  command: "mv {{ dofus_market_bot_path }} {{ dofus_market_bot_path }}_old"
  when: dofus_market_bot_path_stat_result.stat.exists

- name: swap old and new version (2/2)
  command: "mv {{ dofus_market_bot_path }}_new {{ dofus_market_bot_path }}"

- name: create or truncate log file
  copy:
    content: ""
    dest: "{{ dofus_market_bot_log_file }}"
    force: no
    mode: 0644
    group: "{{ dofus_market_bot_user }}"
    owner: "{{ dofus_market_bot_user }}"

- name: start service
  service:
    name: "{{ dofus_market_bot_service_name }}"
    enabled: yes
    state: started

- name: clean old version
  file:
    path: "{{ dofus_market_bot_path }}_old"
    state: absent
  when: dofus_market_bot_path_stat_result.stat.exists

- name: clean local archive
  file:
    path: "/tmp/{{ dofus_market_bot_path | basename }}_new.tgz"
    state: absent
  delegate_to: localhost
  become: false

- name: clean local build
  file:
    path: "/tmp/{{ dofus_market_bot_path | basename }}_new"
    state: absent
  delegate_to: localhost
  become: false

