- hosts: apiserver
  become: yes
  roles:
    - postgresql
    - grafana
    - nginx
    - datadog
    - dotnet
    - dofus-data-exporter
    - dofus-market-api
- hosts: botserver
  become: yes
  roles:
    # - datadog
    # - dotnet
    - dofus-market-bot
