---
- name: Add Microsoft package signing key to the list of trusted keys
  apt:
    deb: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb

- name: Make sure HTTPS is supported by apt
  apt:
    name: apt-transport-https
    state: present

- name: Install .NET Core Runtime
  apt:
    name: "aspnetcore-runtime-{{ dotnet_version }}"
    state: present
    update_cache: yes

- name: Install Datadog .NET Tracer
  apt:
    deb: "https://github.com/DataDog/dd-trace-dotnet/releases/download/v{{ datadog_dotnet_tracer_version }}/datadog-dotnet-apm_{{ datadog_dotnet_tracer_version }}_amd64.deb"

- name: Initialize Datadog .NET Tracer
  command: /opt/datadog/createLogPath.sh
