---
- name: add official repository of Grafana
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
    update_cache: no

- name: add Grafana package signing key to the list of trusted keys
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: install Grafana
  apt:
    name: grafana
    update_cache: yes

- name: create configuration file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: 0640
    owner: root
    group: grafana

- name: restart Grafana
  service:
    name: grafana-server
    enabled: yes
    state: restarted
