namespace Dofus.Types
{
    public enum Breed
    {
        Undefined = 0,
        Feca = 1,
        Osamodas = 2,
        Enutrof = 3,
        Sram = 4,
        Xelor = 5,
        Ecaflip = 6,
        Eniripsa = 7,
        Iop = 8,
        Cra = 9,
        Sadida = 10,
        Sacrieur = 11,
        Pandawa = 12,
        Roublard = 13,
        Zobal = 14,
        Steamer = 15,
        Eliotrope = 16,
        Huppermage = 17,
        Ouginak = 18,
        Summoned = -1,
        Monster = -2,
        MonsterGroup = -3,
        Npc = -4,
        HumanVendor = -5,
        TaxCollector = -6,
        Mutant = -7,
        MutantInDungeon = -8,
        MountOutside = -9,
        Prism = -10,
        Incarnation = -11,
    }
}
