---
- name: Install DataDog
  include_role:
    name: datadog.datadog
  vars:
    datadog_agent_major_version: "7"
    datadog_config:
      logs_enabled: true
      apm_config: # tracing
        enabled: true
      process_config: # live processes
        enabled: "true"
    datadog_checks:
      nginx:
        init_config:
        instances:
        - nginx_status_url: http://localhost:81/nginx_status
        logs:
        - type: file
          path: /var/log/nginx/access.log
          service: nginx
          source: nginx
        - type: file
          path: /var/log/nginx/error.log
          service: nginx
          source: nginx
      postgres:
        init_config:
        instances:
        - host: localhost
          port: 5432
          dbname: "{{ dofus_market_db }}"
          username: "{{ datadog_db_user }}"
        logs:
        - type: file
          path: /var/log/postgresql/postgresql.csv
          service: postgresql
          source: postgresql
          log_processing_rules:
          - type: multi_line
            pattern: \d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])
            name: new_log_start_with_date
      csharp:
        init_config:
        instances:
        logs:
        - type: file
          path: "{{ dofus_market_bot_log_file }}"
          service: "{{ dofus_market_bot_service_name }}"
          source: csharp
      go:
        init_config:
        instances:
        logs:
          - type: file
            path: /var/log/grafana/grafana.log
            service: grafana
            source: grafana
