---
- name: Install DataDog
  include_role:
    name: datadog.datadog
  vars:
    datadog_agent_major_version: "7"
    datadog_config:
      logs_enabled: true
      apm_config: # tracing
        enabled: true
      process_config: # live processes
        enabled: "true"
